name: Orbiter Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Orbiter
        uses: orbiterhost/orbiter-github-actions@v0.0.6

